In [1]:
import numpy as np

In [2]:
l = [[1,2,3],[4,5,6]]

In [3]:
type(l)

list

In [4]:
l[0]

[1, 2, 3]

In [5]:
l[1]

[4, 5, 6]

In [7]:
l[0][0]

1

In [8]:
for i,a in enumerate(l):
    for j,b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [9]:
import numpy as np
np.__version__

'1.19.5'

In [10]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [11]:
np.ndarray.__name__

'ndarray'

In [12]:
type(np.ndarray.var)

method_descriptor

In [14]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) !=type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [15]:
l = [1,2,3,4]

In [16]:
a = np.array(l)

In [17]:
a

array([1, 2, 3, 4])

In [18]:
type(a)

numpy.ndarray

In [28]:
t = (1,2,3,4)

In [29]:
b = np.array(t)

In [30]:
type(b)

numpy.ndarray

In [31]:
a.data

In [32]:
a.data.obj

array([1, 2, 3, 4])

In [33]:
type(a.data.obj)

numpy.ndarray

In [34]:
c = b

In [35]:
c.base is b.base

True

In [38]:
c[0] = 100

In [39]:
c

array([100,   2,   3,   4])

In [40]:
b

array([100,   2,   3,   4])

In [41]:
d = np.array(b)

In [42]:
d[0] = 99

In [43]:
d

array([99,  2,  3,  4])

In [44]:
b

array([100,   2,   3,   4])

In [45]:
e = np.array(l, dtype=np.float)

In [46]:
e

array([1., 2., 3., 4.])

In [48]:
e.dtype

dtype('float64')

In [49]:
a2 = np.array([[1,2,3],[4,5,6]])

In [50]:
a2.shape

(2, 3)

In [51]:
a2.ndim

2

In [52]:
a2.dtype

dtype('int64')

In [53]:
a2.itemsize

8

In [54]:
a2.size

6

In [55]:
a2.strides

(24, 8)

In [56]:
a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [57]:
a2.ravel()

array([1, 2, 3, 4, 5, 6])

In [58]:
a

array([1, 2, 3, 4])

In [59]:
l

[1, 2, 3, 4]

In [60]:
a[0]

1

In [61]:
l[0]

1

In [62]:
l2 = [[1,2,3],[4,5,6]]

In [63]:
l2

[[1, 2, 3], [4, 5, 6]]

In [64]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
try:
    l2[0,1]
except Exception as e :
    print(e)

list indices must be integers or slices, not tuple


In [67]:
l2[0][1]

2

In [68]:
type(a2[0,1])

numpy.int64

In [69]:
a2[0,1].item()

2

In [70]:
type(a2[0,1].item())

int

In [71]:
a2[0,1].real

2

In [72]:
a2[0,1].imag

0

In [73]:
na = np.array([[[1,2,3,],[4,5,6]],[[1,2,3,],[4,5,6]]])

In [74]:
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [75]:
na.ndim

3

In [76]:
na.shape

(2, 2, 3)

In [77]:
na[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
na[0].shape

(2, 3)

In [79]:
na.__array_interface__

{'data': (94829498063568, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (2, 2, 3),
 'version': 3}

In [80]:
na.strides

(48, 24, 8)

In [81]:
na.__array_interface__['data'][0]

94829498063568

In [82]:
len(na.data.tobytes())

96

In [83]:
na.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [84]:
a = np.array([1,2,3,4])

In [85]:
a

array([1, 2, 3, 4])

In [86]:
a.data

In [87]:
mem = memoryview(a)

In [88]:
mem

In [89]:
a.data[0]

1

In [90]:
a.data.obj

array([1, 2, 3, 4])

In [91]:
a.data.obj

array([1, 2, 3, 4])

In [92]:
a.data.obj[0]

1

In [93]:
a.dtype

dtype('int64')

In [94]:
a.itemsize

8

In [95]:
a.data.hex()

'0100000000000000020000000000000003000000000000000400000000000000'

In [96]:
b = np.array([999,9999,99999,999999])

In [97]:
b.data.hex()[:8]

'e7030000'

In [98]:
hex(999)

'0x3e7'

In [99]:
int('0x3e7',16)

999

In [100]:
divmod(999,16)

(62, 7)

In [101]:
divmod(62,16)

(3, 14)

In [102]:
divmod(3,16)

(0, 3)

In [103]:
a.size

4

In [104]:
for i in range(a.size) :
    print(a[i])

1
2
3
4


In [105]:
a.flat

In [106]:
for i in a.flat :
    print(i)

1
2
3
4


In [107]:
c = np.array([1,2,3,4],dtype=np.float_)

In [108]:
c

array([1., 2., 3., 4.])

In [109]:
x = np.frombuffer(c)

In [110]:
x

array([1., 2., 3., 4.])

In [111]:
x.dtype

dtype('float64')

In [112]:
x[0]

1.0

In [113]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [114]:
x.base is c

True

In [115]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [117]:
np.ndarray.__bases__

(object,)

In [119]:
np.matrix.__bases__

(numpy.ndarray,)

In [120]:
l1 = np.array([1,2,3,4,5,6,7,8])

In [121]:
l1.shape

(8,)

In [122]:
m1 = np.matrix([1,2,3,4,5,6,7,8])

In [123]:
m1.shape

(1, 8)

In [124]:
l2 = l1.reshape(2,4)

In [125]:
l2.shape

(2, 4)

In [126]:
m2 = m1.reshape(2,4)

In [127]:
m2.shape

(2, 4)

In [128]:
l3 = l2.reshape(2,2,2)

In [129]:
try:
    m3 = m2.reshape(2,2,2)
except Exception as e :
    print(" 예외 ",e)

 예외  shape too large to be a matrix.


In [130]:
m2_1 = np.asmatrix(l1).reshape(2,4)

In [131]:
m2_1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [132]:
np.ndarray.__bases__

(object,)

In [133]:
np.matrix.__base__

numpy.ndarray

In [134]:
l1 = np.array([1,2,3,4,5,6,7,8])

In [135]:
l1.shape

(8,)

In [136]:
m1 = np.matrix([1,2,3,4,5,6,7,8])

In [137]:
m1.shape

(1, 8)

In [138]:
l2 = l1.reshape(2,4)

In [139]:
l2.shape

(2, 4)

In [140]:
m2 = m1.reshape(2,4)

In [141]:
m2.shape

(2, 4)

In [142]:
l3 = l2.reshape(2,2,2)

In [144]:
try:
    m3=m2.reshape(2,2,2)
except Exception as e :
    print( " 예외 ", e)

 예외  shape too large to be a matrix.


In [145]:
m2_1 = np.asmatrix(l1).reshape(2,4)

In [146]:
m2_1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [147]:
l2 *l2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [149]:
try:
    m2*m2
except Exception as e :
    print(e)

shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)


In [150]:
np.multiply(m2,m2)

matrix([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

In [151]:
nd_ = set(dir(np.ndarray))

In [152]:
md_ = set(dir(np.matrix))

In [153]:
md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [154]:
m4 = np.mat('1 2; 3 4')

In [155]:
m4

matrix([[1, 2],
        [3, 4]])

In [156]:
m4.A

array([[1, 2],
       [3, 4]])

In [157]:
m4.getA()

array([[1, 2],
       [3, 4]])

In [158]:
m4.H

matrix([[1, 3],
        [2, 4]])

In [159]:
M4.T

NameError: name 'M4' is not defined

In [160]:
from numpy import linalg

In [161]:
linalg.inv(m4)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [163]:
m4.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [164]:
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [165]:
try:
    linalg.inv(m2)
except Exception as e :
    print(e)

Last 2 dimensions of the array must be square
